### PR TITLE
 cleanup, upgrade deps, prettier and easier to read changes visualizer 

### PR DESCRIPTION
**Pull request by phiresky**

### CODE REVIEW

**Comment by phiresky** [comment]
adds more inline stuff to have more information at first glance. screenshot:

image

**Comment by Venryx** [comment]
Thanks for the pull-request! Will look this over soon.

**Comment by phiresky** [comment]
I had to add some `any` types to the `Change` type. I assume they were better previously, not sure why it's broken now. I also opened https://github.com/mobxjs/mobx/pull/2389 to actually type the mobx spy function

**Comment by Venryx** [comment]
Merged, thanks for the contribution.

**Pull request merged**
